# Objet

Répétition du cours N° 13 - [PYTHON NUMPY BROADCASTING (13/30)](https://www.youtube.com/watch?v=lIESSFHGalA&list=PLO_fdPEVlfKqMDNmCFzQISI2H_nJcEDJq&index=14)

In [ ]:
import os
from ml_jpy_commons import *

[project_dir]\data\ exists
[project_dir]\data\csv\ exists


## Suite ici, mais le début fait en pur Python avec PyCharm

[PYTHON NUMPY BROADCASTING (13/30)](https://www.youtube.com/watch?v=lIESSFHGalA&list=PLO_fdPEVlfKqMDNmCFzQISI2H_nJcEDJq&index=14)

Broadcasting : extension implicite des dimensions.

In [ ]:
import numpy as np

a = np.random.randint(0, 10, [2, 3])
b = np.ones((2, 3))

In [ ]:
a

array([[1, 5, 0],
       [7, 5, 5]])

In [ ]:
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a + b

array([[2., 6., 1.],
       [8., 6., 6.]])

In [ ]:
c = b = np.ones((1, 3))

In [ ]:
a + c

array([[2., 6., 1.],
       [8., 6., 6.]])

In [ ]:
d = np.array([1, 2, 3, 4])
d = np.transpose([d])
print(d)
e = np.array([5, 6, 7])
print(e)
d + e

[[1]
 [2]
 [3]
 [4]]
[5 6 7]


array([[ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11]])