# 6. Transformations d'ensembles de données

scikit-learn fournit une bibliothèque de transformateurs, qui peuvent nettoyer (voir [6.3. Prétraitement des données](https://scikit-learn.org/stable/modules/preprocessing.html#preprocessing)), réduire (voir [6.5. Réduction de dimensionnalité non supervisée](https://scikit-learn.org/stable/modules/unsupervised_reduction.html#data-reduction)), étendre (voir [6.7. Approximation du noyau](https://scikit-learn.org/stable/modules/kernel_approximation.html#kernel-approximation)) ou générer (voir [6.2. Extraction de caractéristiques](https://scikit-learn.org/stable/modules/feature_extraction.html#feature-extraction)) des représentations d'entités.

Comme d'autres estimateurs, ceux-ci sont représentés par des classes avec une méthode d'ajustement `fit`, qui apprend les paramètres du modèle (par exemple, la moyenne et l'écart type pour la normalisation) à partir d'un ensemble d'apprentissage, et une méthode de transformation `transform` qui applique ce modèle de transformation à de nouvelles données. `fit_transform` peut être plus pratique et efficace pour modéliser et transformer simultanément les données d'apprentissage.

La combinaison de tels transformateurs, en parallèle ou en série, est traitée dans [6.1. Pipelines et estimateurs composites](https://scikit-learn.org/stable/modules/compose.html#combining-estimators). [6.8. Les métriques par paires, es Affinités et les Noyaux](https://scikit-learn.org/stable/modules/metrics.html#metrics) couvrent la transformation des espaces de caractéristiques en matrices d'affinité, tandis que la [6.9. transformation de la cible de prédiction (y)](https://scikit-learn.org/stable/modules/preprocessing_targets.html#preprocessing-targets) considère les transformations de l'espace cible (par exemple, les étiquettes catégorielles) à utiliser dans scikit-learn.

✔ 6.1. Pipelines et estimateurs composites
* ✔ 6.1.1. Pipeline : estimateurs de chaînage
* ✔ 6.1.2. Transformer la cible en régression
* ✔ 6.1.3. FeatureUnion : espaces d'entités composites
* ✔ 6.1.4. ColumnTransformer pour les données hétérogènes
* ✔ 6.1.5. Visualisation des estimateurs composites

✔ 6.2. Extraction de caractéristiques
* ✔ 6.2.1. Chargement de caractéristiques à partir de dicts
* ✔ 6.2.2. Hachage des caractéristiques
* ✔ 6.2.3. Extraction de caractéristiques de texte
* ✔ 6.2.4. Extraction de caractéristiques d'image

6.3. Prétraitement des données
* 6.3.1. Standardisation, ou suppression de la moyenne et mise à l'échelle de la variance
* 6.3.2. Transformation non linéaire
* 6.3.3. Normalisation
* ✔ 6.3.4. Encodage des caractéristiques catégorielles
* 6.3.5. Discrétisation
* 6.3.6. Imputation des valeurs manquantes
* 6.3.7. Génération de caractéristiques polynomiales
* 6.3.8. Transformateurs personnalisés

6.4. Imputation des valeurs manquantes
* 6.4.1. Imputation univariée vs imputation multivariée
* 6.4.2. Imputation de caractéristique univariée
* 6.4.3. Imputation de caractéristiques multivariées
* 6.4.4. Références
* 6.4.5. Imputation des plus proches voisins
* 6.4.6. Marquage des valeurs imputées
* 6.4.7. Estimateurs qui gèrent les valeurs NaN

6.5. Réduction de dimensionnalité non supervisée
* 6.5.1. ACP : analyse en composantes principales
* 6.5.2. Projections aléatoires
* 6.5.3. Agglomération de caractéristiques

6.6. Projection aléatoire
* 6.6.1. Le lemme de Johnson-Lindenstrauss
* 6.6.2. Projection aléatoire gaussienne
* 6.6.3. Projection aléatoire clairsemée
* 6.6.4. Transformation inverse

6.7. Approximation du noyau
* 6.7.1. Méthode Nystroem pour l'approximation du noyau
* 6.7.2. Noyau de fonction de base radiale
* 6.7.3. Additif Chi Squared Kernel
* 6.7.4. Noyau au carré de chi asymétrique
* 6.7.5. Approximation du noyau polynomial via Tensor Sketch
* 6.7.6. Détails mathématiques

6.8. Métriques par paires, affinités et noyaux
* 6.8.1. Similitude cosinus
* 6.8.2. Noyau linéaire
* 6.8.3. Noyau polynomial
* 6.8.4. Noyau sigmoïde
* 6.8.5. Noyau RBF
* 6.8.6. Noyau laplacien
* 6.8.7. Noyau du chi carré

✔ 6.9. Transformer la cible de prédiction (y)
* ✔ 6.9.1. Binarisation des étiquettes
* ✔ 6.9.2. Encodage des étiquettes

# 6.9. Transformer la cible de prédiction (y) | Transforming the prediction target (y)

Ce sont des transformateurs qui ne sont pas destinés à être utilisés sur des caractéristiques, uniquement sur des cibles d'apprentissage supervisé. Voir aussi [6.1. Transformer la cible en régression](https://scikit-learn.org/stable/modules/compose.html#transformed-target-regressor) si vous souhaitez transformer la cible de prédiction pour l'apprentissage, mais évaluer le modèle dans l'espace d'origine (non transformé).

## 6.9.1. Binarisation des étiquettes | Label binarization

### 6.9.1.1. LabelBinarizer

[`LabelBinarizer`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelBinarizer.html#sklearn.preprocessing.LabelBinarizer) est une classe utilitaire permettant de créer une [matrice d'indicateurs d'étiquettes](https://scikit-learn.org/stable/glossary.html#term-label-indicator-matrix) à partir d'une liste d'étiquettes [multiclasses](https://scikit-learn.org/stable/glossary.html#term-multiclass) :

In [1]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
lb.fit([1, 2, 6, 4, 2])
# LabelBinarizer()
lb.classes_
# array([1, 2, 4, 6])
lb.transform([1, 6])
# array([[1, 0, 0, 0],
#       [0, 0, 0, 1]])

array([[1, 0, 0, 0],
       [0, 0, 0, 1]])

L'utilisation de ce format peut permettre une classification multiclasse dans les estimateurs qui prennent en charge le format de matrice d'indicateur d'étiquette.

**Avertissement** : LabelBinarizer n'est pas nécessaire si vous utilisez un estimateur qui prend déjà en charge les données [multiclasses](https://scikit-learn.org/stable/glossary.html#term-multiclass).

Pour plus d'informations sur la classification multiclasse, reportez-vous à la section [1.12.1. Classification multiclasse](https://scikit-learn.org/stable/modules/multiclass.html#multiclass-classification).

### 6.9.1.2. MultiLabelBinarizer

Dans l'apprentissage [multiétiquette](https://scikit-learn.org/stable/glossary.html#term-multilabel), l'ensemble conjoint de tâches de classification binaire est exprimé avec un tableau d'indicateurs binaires d'étiquette : chaque échantillon est une ligne d'un tableau 2d de forme `(n_échantillons, n_classes)` avec des valeurs binaires où l'un, c'est-à-dire les éléments non nuls, correspond au sous-ensemble d'étiquettes pour cet échantillon. Un tableau tel que `np.array([[1, 0, 0], [0, 1, 1], [0, 0, 0]])` représente l'étiquette 0 dans le premier échantillon, les étiquettes 1 et 2 dans le deuxième échantillon, et aucune étiquette dans le troisième échantillon.

La production de données multiétiquettes sous la forme d'une liste d'ensembles d'étiquettes peut être plus intuitive. Le transformateur [`MultiLabelBinarizer`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MultiLabelBinarizer.html#sklearn.preprocessing.MultiLabelBinarizer) peut être utilisé pour convertir entre une collection de collections d'étiquettes et le format d'indicateur :

In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer
y = [[2, 3, 4], [2], [0, 1, 3], [0, 1, 2, 3, 4], [0, 1, 2]]
MultiLabelBinarizer().fit_transform(y)
# array([[0, 0, 1, 1, 1],
#        [0, 0, 1, 0, 0],
#        [1, 1, 0, 1, 0],
#        [1, 1, 1, 1, 1],
#        [1, 1, 1, 0, 0]])

Pour plus d'informations sur la classification multiétiquette, reportez-vous à la section [1.12.2. Classification multiétiquette](https://scikit-learn.org/stable/modules/multiclass.html#multilabel-classification).

## 6.9.2. Encodage des étiquettes | Label encoding

[`LabelEncoder`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder) est une classe utilitaire permettant de normaliser les étiquettes de sorte qu'elles ne contiennent que des valeurs comprises entre 0 et n_classes-1. Ceci est parfois utile pour écrire des routines Cython efficaces. [`LabelEncoder`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder) peut être utilisé comme suit :

In [2]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit([1, 2, 2, 6])
# LabelEncoder()
le.classes_
# array([1, 2, 6])
le.transform([1, 1, 2, 6])
# array([0, 0, 1, 2])
le.inverse_transform([0, 0, 1, 2])
# array([1, 1, 2, 6])

array([1, 1, 2, 6])

Il peut également être utilisé pour transformer des étiquettes non numériques (tant qu'elles sont hachables et comparables) en étiquettes numériques :

In [ ]:
le = preprocessing.LabelEncoder()
le.fit(["paris", "paris", "tokyo", "amsterdam"])
# LabelEncoder()
list(le.classes_)
# ['amsterdam', 'paris', 'tokyo']
le.transform(["tokyo", "tokyo", "paris"])
# array([2, 2, 1])
list(le.inverse_transform([2, 2, 1]))
# ['tokyo', 'tokyo', 'paris']