In [ ]:
print('Hellooo')

Hellooo


In [ ]:
revenus = [1800, 1500, 2200, 3000, 2172]

In [ ]:
def moyenne(liste):
    return sum(liste)/len(liste)
moyenne(revenus) # => 2135.0

2134.4

In [ ]:
import numpy as np
np.mean(revenus)

2134.4

In [ ]:
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


In [ ]:
a_rev = np.array(revenus)
a_rev

array([1800, 1500, 2200, 3000, 2172])

In [ ]:
a_rev.dtype

dtype('int32')

In [ ]:
a_rev[1] = 1
a_rev

array([1800,    1, 2200, 3000, 2172])

In [ ]:
a_rev[1:5:2]

array([   1, 3000])

In [ ]:
a_rev[::-1]

array([2172, 3000, 2200,    1, 1800])

In [ ]:
a_rev[a_rev > 2000]

array([2200, 3000, 2172])

In [ ]:
a_rev > 2000

array([False, False,  True,  True,  True])

In [ ]:
a_rev[(a_rev > 2000) & (a_rev < 2500)]

array([2200, 2172])

In [ ]:
a_rev[(a_rev > 2000) & (a_rev < 2500)] = a_rev[(a_rev > 2000) & (a_rev < 2500)] / 2

In [ ]:
a_rev

array([1800,    1, 1100, 3000, 1086])

In [ ]:
len(a_rev)
a_rev.shape

(5,)

In [ ]:
a_rev.mean()

1397.4

In [ ]:
np.ma.median(a_rev)

1100.0

In [ ]:
a_rev.argmin()

1

In [ ]:
a_rev.sort()
a_rev

array([   1, 1086, 1100, 1800, 3000])

In [ ]:
a_rev.sum()

6987

In [ ]:
tab1 = np.array([[1, 2],
    [3, 4],
    [5, 6]])

tab2 = np.array([[1, 2, 3],
        [4, 5, 6]])
print(tab1)
tab2

[[1 2]
 [3 4]
 [5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.random.randint(0, 2, size = (2, 3, 5))

array([[[1, 0, 1, 1, 1],
        [1, 0, 0, 1, 0],
        [0, 1, 0, 0, 0]],

       [[0, 0, 1, 0, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 0, 0, 1]]])

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 10], [15, 20]])
C = np.array([[2, 4, 6], [8, 10, 12]])

A+B
AC = A @ B
AC

array([[ 35,  50],
       [ 75, 110]])

In [ ]:
a = np.linspace(5, 10, 11)
print(a)
a[-3:]

[ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10. ]


array([ 9. ,  9.5, 10. ])

In [ ]:
import pandas as pd
df = pd.read_csv('~/Downloads/P2C1_clients/clients.csv')
#display(df.head())
#display(df.tail())
display(df)
df.shape
df.dtypes
display(df.values)

identifiant                            email                nom genre
0              0        LaurentDagenais@rhyta.com   Laurent Dagenais     M
1              1            GuyMarois@fleckens.hu         Guy Marois     M
2              2        BeaufortLesage@einrot.com    Beaufort Lesage     M
3              3        RussellDurand@armyspy.com     Russell Durand     M
4              4             AlexisRiel@rhyta.com        Alexis Riel     M
..           ...                              ...                ...   ...
223          223  ClaudeDandonneau@jourrapide.com  Claude Dandonneau     F
224          224    ApollineMichaud@superrito.com   Apolline Michaud     F
225          225       PascalineBeaudry@rhyta.com  Pascaline Beaudry     F
226          226     FleurCaouette@jourrapide.com     Fleur Caouette     F
227          227      FrancisMasse@jourrapide.com      Francis Masse     M

[228 rows x 4 columns]

array([[0, 'LaurentDagenais@rhyta.com', 'Laurent Dagenais', 'M'],
       [1, 'GuyMarois@fleckens.hu', 'Guy Marois', 'M'],
       [2, 'BeaufortLesage@einrot.com', 'Beaufort Lesage', 'M'],
       [3, 'RussellDurand@armyspy.com', 'Russell Durand', 'M'],
       [4, 'AlexisRiel@rhyta.com', 'Alexis Riel', 'M'],
       [5, 'LeonLapresse@cuvox.de', 'Leon Lapresse', 'M'],
       [6, 'OrvilleRouthier@gustr.com', 'Orville Routhier', 'M'],
       [7, 'AgramantPepin@dayrep.com', 'Agramant Pepin', 'M'],
       [8, 'AiglentinaLambert@fleckens.hu', 'Aiglentina Lambert', 'F'],
       [9, 'TheodoreClavet@teleworm.us', 'Theodore Clavet', 'M'],
       [10, 'ByronLefebvre@jourrapide.com', 'Byron Lefebvre', 'M'],
       [11, 'FlorusDevoe@einrot.com', 'Florus Devoe', 'M'],
       [12, 'NormandArsenault@armyspy.com', 'Normand Arsenault', 'M'],
       [13, 'AcelineHughes@jourrapide.com', 'Aceline Hughes', 'F'],
       [14, 'GastonBrisette@superrito.com', 'Gaston Brisette', 'M'],
       [15, 'AgateGrandbois@gus

In [ ]:
clients = df
emails = clients['email']
#vars = ['nom', 'email']
#clients[vars]
extract = clients[['nom', 'email']]
print(type(clients))
print(type(extract))
print(type(emails))
print(emails.dtypes)
print(emails.shape)
print(emails.head)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
object
(228,)
<bound method NDFrame.head of 0            LaurentDagenais@rhyta.com
1                GuyMarois@fleckens.hu
2            BeaufortLesage@einrot.com
3            RussellDurand@armyspy.com
4                 AlexisRiel@rhyta.com
                    ...               
223    ClaudeDandonneau@jourrapide.com
224      ApollineMichaud@superrito.com
225         PascalineBeaudry@rhyta.com
226       FleurCaouette@jourrapide.com
227        FrancisMasse@jourrapide.com
Name: email, Length: 228, dtype: object>


In [ ]:
#clients[["email"]]
clients['identifiant'] += 1
clients
clients['new_id'] = range(0, len(clients))
clients
#clients = clients.drop(columns=['new_id', 'email'])
clients = pd.read_csv('~/Downloads/P2C1_clients/clients.csv')
clients
del clients['email']
clients.pop('genre')
clients

identifiant                nom
0              0   Laurent Dagenais
1              1         Guy Marois
2              2    Beaufort Lesage
3              3     Russell Durand
4              4        Alexis Riel
..           ...                ...
223          223  Claude Dandonneau
224          224   Apolline Michaud
225          225  Pascaline Beaudry
226          226     Fleur Caouette
227          227      Francis Masse

[228 rows x 2 columns]

In [ ]:
clients = pd.read_csv('~/Downloads/P2C1_clients/clients.csv')
clients.rename(columns={'identifiant' : 'id', 'email' : 'mel'}, inplace=True)
#clients['id'].astype(float)
#clients.dtypes
#clients.sort_values('id', ascending = False, inplace = True)
#clients.sort_values(['nom', 'mel'], ascending = [True, False], inplace = True)
#clients
clients

id                              mel                nom genre
0      0        LaurentDagenais@rhyta.com   Laurent Dagenais     M
1      1            GuyMarois@fleckens.hu         Guy Marois     M
2      2        BeaufortLesage@einrot.com    Beaufort Lesage     M
3      3        RussellDurand@armyspy.com     Russell Durand     M
4      4             AlexisRiel@rhyta.com        Alexis Riel     M
..   ...                              ...                ...   ...
223  223  ClaudeDandonneau@jourrapide.com  Claude Dandonneau     F
224  224    ApollineMichaud@superrito.com   Apolline Michaud     F
225  225       PascalineBeaudry@rhyta.com  Pascaline Beaudry     F
226  226     FleurCaouette@jourrapide.com     Fleur Caouette     F
227  227      FrancisMasse@jourrapide.com      Francis Masse     M

[228 rows x 4 columns]

In [ ]:
test = pd.DataFrame(np.arange(12).reshape(3, 4), columns=['A', 'B', 'C', 'D'])
test

A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [ ]:
data = {'fix' : ['a', 'b', 'b', 'a', 'b'], 'col' : [3, 4, 10, 7, 6]}
test = pd.DataFrame(data)
test

fix  col
0   a    3
1   b    4
2   b   10
3   a    7
4   b    6

In [ ]:
test.groupby('fix').mean()

col
fix          
a    5.000000
b    6.666667

In [ ]:
import pandas as pd
notes = pd.read_csv(r'C:\Users\franc\Downloads\notes.csv')
notes

nom          matiere  note
0     Laurent Dagenais         Français    16
1           Guy Marois         Français    13
2      Beaufort Lesage         Français     8
3       Russell Durand         Français    10
4          Alexis Riel         Français    15
..                 ...              ...   ...
79    Agrican Foucault  Physique/Chimie     9
80  Prunella Josseaume  Physique/Chimie     6
81      Yseult Charest  Physique/Chimie    16
82      Dorothee Aupry  Physique/Chimie    17
83       Amaury Reault  Physique/Chimie     8

[84 rows x 3 columns]

In [ ]:
notes.groupby('matiere').mean()


note
matiere                   
Biologie         10.952381
Français         12.857143
Mathématiques    11.333333
Physique/Chimie  11.523810

In [ ]:
moyennes = notes.groupby('nom').mean()
moyennes.reset_index(inplace=True)
moyennes
#moyennes['note'] < 10
#type(moyennes)
bad = moyennes.loc[moyennes['note'] < 10]
bad.shape[0]

6

In [ ]:
notes_hg = pd.read_csv(r'C:\Users\franc\Downloads\notes_sup.csv')
notes_hg
notes = pd.concat([notes, notes_hg])
notes

nom   matiere  note
0     Laurent Dagenais  Français    16
1           Guy Marois  Français    13
2      Beaufort Lesage  Français     8
3       Russell Durand  Français    10
4          Alexis Riel  Français    15
..                 ...       ...   ...
37    Agrican Foucault   Anglais    10
38  Prunella Josseaume   Anglais    20
39      Yseult Charest   Anglais     7
40      Dorothee Aupry   Anglais    11
41       Amaury Reault   Anglais    12

[126 rows x 3 columns]

In [ ]:
notes.groupby('matiere').mean()

note
matiere                       
Anglais              12.428571
Biologie             10.952381
Français             12.857143
Histoire/Géographie  14.047619
Mathématiques        11.333333
Physique/Chimie      11.523810

In [ ]:
notes.pivot_table(index='nom', columns='matiere', values='note')

matiere             Anglais  Biologie  Français  Histoire/Géographie  \
nom                                                                    
Aceline Hughes           18        15        12                   12   
Agate Grandbois          17        19        12                    9   
Agramant Pepin           10         6        17                   20   
Agrican Foucault         10        14        10                   14   
Aiglentina Lambert        7         7        16                   15   
Alexis Riel              13         5        15                   20   
Amaury Reault            12         7         8                   18   
Beaufort Lesage          12         8         8                    8   
Byron Lefebvre           12        15        13                   15   
Dorothee Aupry           11        16        13                   20   
Florus Devoe             12        11        10                   14   
Gaston Brisette           7        17        19                    8   
Guy Marois               11         8        13                   13   
Laurent Dagenais          7        17        16                   18   
Leon Lapresse            13         8        17                   18   
Normand Arsenault        19         6        17                   10   
Orville Routhier          7         6         6                   20   
Prunella Josseaume       20        14        19                    9   
Russell Durand           17        12        10                   19   
Theodore Clavet          19         6         8                    8   
Yseult Charest            7        13        11                    7   

matiere             Mathématiques  Physique/Chimie  
nom                                                 
Aceline Hughes                 13               10  
Agate Grandbois                 9               17  
Agramant Pepin                 18               16  
Agrican Foucault               13                9  
Aiglentina Lambert              6                5  
Alexis Riel                     5               11  
Amaury Reault                  11                8  
Beaufort Lesage                15               18  
Byron Lefebvre                 19                8  
Dorothee Aupry                 13               17  
Florus Devoe                   19               15  
Gaston Brisette                 6               12  
Guy Marois                     17               11  
Laurent Dagenais                7               13  
Leon Lapresse                   7               17  
Normand Arsenault              10                9  
Orville Routhier               12                9  
Prunella Josseaume             11                6  
Russell Durand                  5                7  
Theodore Clavet                16                8  
Yseult Charest                  6               16

In [ ]:
commandes = pd.read_csv(r'C:\Users\franc\Downloads\csv_P2_quizz\commande.csv')
commandes

id  nombre
0    70       2
1    41       4
2    72       2
3    92       8
4    73       1
..   ..     ...
995  37       2
996  83       6
997  44       3
998  23       9
999  15       1

[1000 rows x 2 columns]

In [ ]:
produits = pd.read_csv(r'C:\Users\franc\Downloads\csv_P2_quizz\produits.csv')
produits

id  prix
0    0  24.8
1    1  13.1
2    2  23.7
3    3  16.0
4    4  19.0
..  ..   ...
95  95  21.2
96  96  18.8
97  97   8.9
98  98  20.0
99  99  11.8

[100 rows x 2 columns]

In [ ]:
ventes_vol = commandes.groupby('id').count().sort_values('nombre', ascending=False)
ventes_vol

nombre
id        
66      17
8       17
30      17
65      16
94      16
..     ...
58       4
28       4
95       4
62       4
68       3

[100 rows x 1 columns]

In [ ]:
commandes_ca = pd.merge(commandes, produits, how='left')
commandes_ca['total'] = commandes_ca['nombre'] * commandes_ca['prix']
commandes_ca = commandes_ca.sort_values('total')
commandes_ca


id  nombre  prix  total
911  94       1   5.8    5.8
84   94       1   5.8    5.8
179  92       1   7.4    7.4
710  55       1   8.0    8.0
251  55       1   8.0    8.0
..   ..     ...   ...    ...
333  77      10  28.0  280.0
736  52       9  32.4  291.6
215  19      10  31.6  316.0
879  19      10  31.6  316.0
304  52      10  32.4  324.0

[1000 rows x 4 columns]